/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;



import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import AllReports.AllReport;
import AllReports.ProfileContoller;
import com.mashape.unirest.http.exceptions.UnirestException;
import javax.swing.ImageIcon;

import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.BufferedReader;
import java.io.FileReader;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author masoud
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
      /* important Statement */
    //setUndecorated(true);
    setResizable(false);
    setTitle("One Click Morning");
    
    
        
    Dimension screenSize,frameSize;
    int x,y;
    screenSize=Toolkit.getDefaultToolkit().getScreenSize();
    frameSize=getSize();
    x=(screenSize.width-frameSize.width)/2;
    y=(screenSize.height-frameSize.height)/2;
    setLocation(x, y);
    
    
    //////////// half size
     /*Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int height = screenSize.height;
        int width = screenSize.width;
        setSize(width/2, height/2);
     setLocationRelativeTo(null);   */
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emptyBorder1 = (javax.swing.border.EmptyBorder)javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BTNbrowse = new javax.swing.JButton();
        textField1 = new javax.swing.JTextField();
        createAllDurationsButton = new javax.swing.JButton();
        BTNpaste = new javax.swing.JButton();
        BTNAdd = new javax.swing.JButton();
        BTNdelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list2 = new javax.swing.JList<>();
        jTxtprofile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("One Click Morning");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(102, 102, 102));
        setIconImage(getIconImage());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose your Profile");
        jLabel1.setOpaque(true);

        BTNbrowse.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNbrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Library-Windows-icon.png"))); // NOI18N
        BTNbrowse.setToolTipText("Browse");
        BTNbrowse.setActionCommand("BTNbrowse");
        BTNbrowse.setMaximumSize(new java.awt.Dimension(70, 25));
        BTNbrowse.setMinimumSize(new java.awt.Dimension(70, 25));
        BTNbrowse.setPreferredSize(new java.awt.Dimension(70, 25));
        BTNbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNbrowseActionPerformed(evt);
            }
        });

        textField1.setBackground(new java.awt.Color(153, 153, 153));
        textField1.setToolTipText("Double click to Browse");
        textField1.setPreferredSize(new java.awt.Dimension(7, 23));
        textField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textField1MouseClicked(evt);
            }
        });

        createAllDurationsButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        createAllDurationsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Floppy-Drive-icon.png"))); // NOI18N
        createAllDurationsButton.setToolTipText("Create");
        createAllDurationsButton.setActionCommand("createAllDurationsButton");
        createAllDurationsButton.setMaximumSize(new java.awt.Dimension(70, 25));
        createAllDurationsButton.setMinimumSize(new java.awt.Dimension(70, 25));
        createAllDurationsButton.setPreferredSize(new java.awt.Dimension(70, 25));
        createAllDurationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAllDurationsButtonActionPerformed(evt);
            }
        });

        BTNpaste.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNpaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Actions-edit-paste-icon.png"))); // NOI18N
        BTNpaste.setToolTipText("Paste");
        BTNpaste.setActionCommand("BTNpaste");
        BTNpaste.setMaximumSize(new java.awt.Dimension(70, 25));
        BTNpaste.setMinimumSize(new java.awt.Dimension(70, 25));
        BTNpaste.setPreferredSize(new java.awt.Dimension(70, 25));
        BTNpaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNpasteActionPerformed(evt);
            }
        });

        BTNAdd.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BTNAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Actions-list-add-icon.png"))); // NOI18N
        BTNAdd.setToolTipText("ADD");
        BTNAdd.setActionCommand("BTNAdd");
        BTNAdd.setMaximumSize(null);
        BTNAdd.setMinimumSize(new java.awt.Dimension(93, 69));
        BTNAdd.setPreferredSize(new java.awt.Dimension(93, 69));
        BTNAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAddActionPerformed(evt);
            }
        });

        BTNdelete.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        BTNdelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/Actions-edit-delete-icon.png"))); // NOI18N
        BTNdelete.setToolTipText("Delete");
        BTNdelete.setActionCommand("BTNdelete");
        BTNdelete.setMaximumSize(new java.awt.Dimension(70, 25));
        BTNdelete.setMinimumSize(new java.awt.Dimension(70, 25));
        BTNdelete.setPreferredSize(new java.awt.Dimension(70, 25));
        BTNdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNdeleteActionPerformed(evt);
            }
        });

        list2.setBackground(new java.awt.Color(240, 240, 240));
        list2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list2.setMaximumSize(new java.awt.Dimension(33, 200));
        list2.setMinimumSize(new java.awt.Dimension(33, 200));
        list2.setOpaque(false);
        list2.setPreferredSize(new java.awt.Dimension(33, 200));
        list2.setSelectionBackground(new java.awt.Color(255, 153, 153));
        list2.setSelectionForeground(new java.awt.Color(240, 240, 240));
        list2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(list2);

        jTxtprofile.setEditable(false);
        jTxtprofile.setBackground(new java.awt.Color(102, 102, 102));
        jTxtprofile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTxtprofile.setForeground(new java.awt.Color(204, 204, 204));
        jTxtprofile.setText("Profile 1");
        jTxtprofile.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTxtprofile.setMinimumSize(new java.awt.Dimension(7, 23));
        jTxtprofile.setPreferredSize(new java.awt.Dimension(7, 23));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 8)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Masoud Naji");
        jLabel2.setOpaque(true);
        jLabel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel2AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Profile 1", "Profile 2", "Profile 3", "Profile 4", "Profile 5", "Profile 6", "Profile 7", "Profile 8", "Profile 9", "Profile 10", " " }));
        jComboBox1.setMinimumSize(new java.awt.Dimension(57, 23));
        jComboBox1.setPreferredSize(new java.awt.Dimension(65, 32));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jToggleButton1.setPreferredSize(new java.awt.Dimension(32, 32));
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/play.png"))); // NOI18N
        jButton1.setToolTipText("One Click RUN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/clock.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(BTNAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNdelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNbrowse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNpaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createAllDurationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTNdelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNbrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNpaste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(createAllDurationsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtprofile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      // TODO add your handling code here
      
        String currentDirectory = System.getProperty("user.dir");
        ImageIcon icon = new ImageIcon(currentDirectory+"\\src\\main\\java\\Icon\\sun.png");
        jToggleButton1.setIcon(icon);
     
      
        

    
    }//GEN-LAST:event_formWindowActivated

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        // TODO add your handling code here:
        String currentDirectory = System.getProperty("user.dir");
        // System.out.println("The current working directory is " + currentDirectory);
        ImageIcon icon = new ImageIcon(currentDirectory+"\\src\\main\\java\\Icon\\start.png");
        setIconImage(icon.getImage());
        // for run profile 1 at start
        jTxtprofile.setText("Profile 1");
        list2.setModel(mod2);
        mod2.clear();
        try {
            //  sendkeyfile();
            sendsavefile();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jPanel1AncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // String currentDirectory = System.getProperty("user.dir/Click/Profile 1morning.bat");

        try{
            String fileopen= jTxtprofile.getText();
            System.out.println("user.dir/Click/"+fileopen +"morning.bat");
            String currentDirectory = ("user.dir/Click/"+fileopen +"morning.bat");
            System.out.println(currentDirectory);

            Process p = Runtime.getRuntime().exec(currentDirectory);
            p.waitFor();

        }catch( IOException ex ){
            //Validate the case the file can't be accesed (not enought permissions)

        }catch( InterruptedException ex ){
            //Validate the case the process is being stopped by some external situation

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        // TODO add your handling code here:
        if(jToggleButton1.isSelected()){
            String currentDirectory = System.getProperty("user.dir");
            ImageIcon icon = new ImageIcon(currentDirectory+"\\src\\main\\java\\Icon\\moon.png");
            jToggleButton1.setIcon(icon);

          //  jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
           // jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
            jTxtprofile.setForeground(new java.awt.Color(102, 102, 102));
            textField1.setBackground(new java.awt.Color(204, 204, 255));
            jTxtprofile.setBackground(new java.awt.Color(204, 204, 255));
            jLabel2.setBackground(new java.awt.Color(204, 204, 255));
            jPanel1.setBackground(new java.awt.Color(204, 204, 255));
            jLabel1.setBackground(new java.awt.Color(204, 204, 255));
            jLabel1.setForeground(new java.awt.Color(102, 102, 102));

        } else if(!jToggleButton1.isSelected()){
            String currentDirectory = System.getProperty("user.dir");
            ImageIcon icon = new ImageIcon(currentDirectory+"\\src\\main\\java\\Icon\\sun.png");
            jToggleButton1.setIcon(icon);
            jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        //    jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
            jTxtprofile.setForeground(new java.awt.Color(204, 204, 204));
        //    jTextArea1.setBackground(new java.awt.Color(102, 102, 102));
            textField1.setBackground(new java.awt.Color(153, 153, 153));
            jTxtprofile.setBackground(new java.awt.Color(102, 102, 102));
            jPanel1.setBackground(new java.awt.Color(102, 102, 102));
            jLabel1.setBackground(new java.awt.Color(102, 102, 102));
            jLabel1.setForeground(new java.awt.Color(204, 204, 204));

        }

    }//GEN-LAST:event_jToggleButton1StateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        int result = JOptionPane.showConfirmDialog(frame,"Sure? You want to exit from this Profile? \n All Unsaved Data Will be delete", "Swing Tester",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){
            // System.out.println("You selected: Yes");
            jTxtprofile.setText(jComboBox1.getSelectedItem().toString());
            list2.setModel(mod2);
            mod2.clear();
            try {
                //  sendkeyfile();
                sendsavefile();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if (result == JOptionPane.NO_OPTION){
            System.out.println("You selected: No");
        }else {
            System.out.println("None selected");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        try {
            //Desktop.getDesktop().browse(new URI("mailto:m.naji@inceptionq.com"));
            Desktop.getDesktop().browse(new URI("http://masoudnaji.com/contact/"));
        } catch (IOException | URISyntaxException e1) {
            e1.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel2AncestorAdded

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2AncestorAdded

    private void list2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list2MouseClicked
        textField1.setText((String) list2.getSelectedValue());        // TODO add your handling code here:
    }//GEN-LAST:event_list2MouseClicked

    private void BTNdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNdeleteActionPerformed
        // TODO add your handling code here:
        if (!textField1.getText().isEmpty()) {
            deletSllist();
        } else {
            JOptionPane.showMessageDialog(null, "Please Choose At Leaste One Item");
        }
    }//GEN-LAST:event_BTNdeleteActionPerformed

    private void BTNAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAddActionPerformed
        // TODO add your handling code here:
        if (!textField1.getText().isEmpty()) {
            addTolist();
            textField1.requestFocus();
        } else {
            openbrowser();
            // JOptionPane.showMessageDialog(null, "Please choose your Application or just write or paste URL \r\n to the box below then ADD to List  ");
            textField1.requestFocus();
        }

    }//GEN-LAST:event_BTNAddActionPerformed

    private void BTNpasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNpasteActionPerformed
        // TODO add your handling code here:
        Clipboard c = Toolkit.getDefaultToolkit().getSystemClipboard();
        String past = null;
        try {
            past = (String) c.getContents(null).getTransferData(DataFlavor.stringFlavor);
        } catch (UnsupportedFlavorException unsupportedFlavorException) {
            unsupportedFlavorException.printStackTrace();
        } catch (IOException ioException) {
            ioException.printStackTrace();
        }
        textField1.setText(past);

    }//GEN-LAST:event_BTNpasteActionPerformed

    private void createAllDurationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAllDurationsButtonActionPerformed
        // TODO add your handling code here:
        if (!mod2.isEmpty()) {
            try {
                runallreport();
            } catch (UnirestException unirestException) {
                unirestException.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "The List Is Empty Please add Some  \r\n or Choose one profile");
            try {
                sendsavefile();
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "SomeThing went WRONG Please Restart The Application \r\n if it not works again Just COntact Us");
                Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_createAllDurationsButtonActionPerformed

    private void textField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textField1MouseClicked
        // TODO add your handling code here:
        // openbrowser();
        if(evt.getClickCount()==2){
            openbrowser();
        }

    }//GEN-LAST:event_textField1MouseClicked

    private void BTNbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNbrowseActionPerformed
        // TODO add your handling code here:

        openbrowser();

    }//GEN-LAST:event_BTNbrowseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
                
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAdd;
    private javax.swing.JButton BTNbrowse;
    private javax.swing.JButton BTNdelete;
    private javax.swing.JButton BTNpaste;
    private javax.swing.JButton createAllDurationsButton;
    private javax.swing.border.EmptyBorder emptyBorder1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jTxtprofile;
    private javax.swing.JList<String> list2;
    private javax.swing.JTextField textField1;
    // End of variables declaration//GEN-END:variables
   // DefaultListModel mod = new DefaultListModel();
    DefaultListModel mod2 = new DefaultListModel();
    JFrame frame = new JFrame("Swing Tester");
    
  
    String Profilecurrent =ProfileContoller.profilename; 
    
    
   
        
     
    
    
   
    
 private void deletSllist() {

        int selectedIndex = list2.getSelectedIndex();
        if (selectedIndex != -1) {
            mod2.remove(selectedIndex);
        }
    }

    private void addTolist() {


        list2.setModel(mod2);
        mod2.addElement(textField1.getText());
        textField1.setText(null);

    }


 public String getDataFromGui() {
        return "ok";

    }

    public void runallreport() throws UnirestException {


      //  System.out.println("list1.getModel().getSize() = " + list2.getModel().getSize());        //test
        ArrayList<Object> args = new ArrayList<Object>();
        for (int i = 0; i < list2.getModel().getSize(); i++) {
            args.add(list2.getModel().getElementAt(i));
        }
     //   System.out.println("arrayList = " + args);    //test
        ////Convert arraylist to object
        Object[] arr = args.toArray();
      //  System.out.println(Arrays.toString(arr));    //test
        //// Convert Arraylist To String Array
        String[] starry = args.toArray(new String[args.size()]);
      //  System.out.println(Arrays.toString(starry));    //test
        ///// Send String[] to Allreport main class    
        AllReport.main(starry);
    }


      public static void getsaveddata(String mySavedata) {

        String key;
        key = mySavedata;
        ////  System.out.println("mysavedat " + key);


    }

   /* public void sendkeyfile() throws FileNotFoundException { //only way to read and send to texbox1 old key

       try {
            // TODO add your handling code here:
                      mod.clear();
         String filePath = "C:/MorningClick/Click/morning.bat";
         File file = new File(filePath);

            BufferedReader br = new BufferedReader(new FileReader(file));
            Object[] lines = br.lines().toArray();
            jTextPane1.setText("text --- "+lines.length);
            for(int i = 0; i < lines.length; i++){           
                    jTextPane1.setText("text --- "+lines.length);         
                   String line = lines[i].toString();
                   mod.add(i,line);

            }
           // 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        mod.remove(0);
        list1.setModel(mod);
        mod.remove(1);     
        list1.setModel(mod);
        //mod.remove(0);
    }*/

   public void sendsavefile() throws FileNotFoundException { //only way to read and send to texbox1 old key

       String Jselect=jComboBox1.getSelectedItem().toString();
       ProfileContoller.profilename = jTxtprofile.getText();
       
       try {
            // TODO add your handling code here:
                list2.setModel(mod2);
                mod2.clear();
              //  "C:/MorningClick/Click/"+Jselect+"morning.txt";
                        //    "user.dir/Click"+Profilecurrent +"morning.bat"
         String filePath = "user.dir/Click/"+Jselect+"morning.txt";
         File file = new File(filePath);

            BufferedReader br = new BufferedReader(new FileReader(file));
            Object[] lines = br.lines().toArray();
            for(int i = 0; i < lines.length; i++){
                   String line = lines[i].toString();
                   mod2.add(i,line);
            }
           // 
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    private String teststring(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void openbrowser(){
        try {
                    FileDialog fd = new FileDialog(new JFrame());
                    fd.setVisible(true);
                    
                    File[] f = fd.getFiles();
                    if (f.length > 0) {
                        System.out.println(fd.getFiles()[0].getAbsolutePath());
                        textField1.setText(fd.getFiles()[0].getAbsolutePath());
                    }
                } catch (IllegalArgumentException iae) {
                    System.out.println("File Not Found");

                    ////// if not using windows open java file chooser
                    JFileChooser chooser = new JFileChooser();
                    int status = chooser.showOpenDialog(null);
                    if (status == JFileChooser.APPROVE_OPTION) {
                        File file = chooser.getSelectedFile();
                        if (file == null) {
                            return;
                        }

                        String fileName = chooser.getSelectedFile().getAbsolutePath();
                        textField1.setText((String) fileName);
                    }
                }
    }
    


}
